#!/usr/bin/env php
<?php 
use MaplePHP\Foundation\Kernel\Kernel;
$dir = dirname(__FILE__).'/';
if(is_file("{$dir}app/Libraries/Foundation/autoload.php")) {
	require_once("{$dir}app/Libraries/Foundation/autoload.php");
}
if(is_file("{$dir}vendor/autoload.php")) {
	require_once("{$dir}vendor/autoload.php");
}
$kernel = new Kernel($dir);
$kernel->runCli($argv);
