#!/usr/bin/env php
<?php

use MaplePHP\Foundation\Kernel\Kernel;
$dir = dirname(__FILE__).'/';
require_once("{$dir}app/Libraries/Foundation/autoload.php");
$kernel = new Kernel($dir);
$kernel->runCli($argv);
